# Belajar Python Pandas

## Video Workshop
Panduan dan pembahasan materi worskhop ini bisa diakses melalui video berikut ini:

In [1]:
# from IPython.display import YouTubeVideo
# YouTubeVideo('UvpBJZ_UKk0')

## Kebutuhan Instalasi
Untuk dapat menjalankan Notebook ini, Anda butuh untuk melakukan instalasi [Anaconda](https://www.anaconda.com/distribution/) pada komputer yang Anda miliki.

## Import Pandas

In [2]:
import pandas as pd

## Mengenal DataFrame

#### Membuat DataFrame sederhana

In [3]:
pd.DataFrame(data={'Minuman': ['Bandrek', 'Kopi Hitam'], 
                   'Harga': [4500, 3200]})
# jumlah data pada masing2 value harus sama ! value 1 = value 2 = 2

      Minuman  Harga
0     Bandrek   4500
1  Kopi Hitam   3200

#### Mengenal index pada DataFrame

In [81]:
pd.DataFrame(data={'Budi': ['suka', 'suka'], 
                   'Wati': ['tidak suka', 'suka.']},
             index=['Mangga', 'Jambu'])

        Budi        Wati
Mangga  suka  tidak suka
Jambu   suka       suka.

## Mengenal Series

In [5]:
pd.Series(data=[100, 150, 200, 250, 300])

0    100
1    150
2    200
3    250
4    300
dtype: int64

In [6]:
pd.Series(data=[3000, 3500, 40000], index=['Mangga', 'Pisang', 'Jambu'], name='Harga Buah')

Mangga     3000
Pisang     3500
Jambu     40000
Name: Harga Buah, dtype: int64

## Memuat File CSV ke dalam DataFrame

In [83]:
wine_df = pd.read_csv('./dataset/winemag-data-130k-v2.csv')
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [8]:
wine_df.head(10)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam

#### Melihat dimensi DataFrame dengan attribute ```shape```

In [9]:
wine_df.shape

(129971, 14)

#### Menggunakan salah satu kolom sebagai index

In [10]:
wine_df = pd.read_csv('./dataset/winemag-data-130k-v2.csv', index_col=0)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [11]:
wine_df.shape

(129971, 13)

## Menyimpan DataFrame ke dalam File CSV

In [12]:
minuman_df = pd.DataFrame(data={'Minuman': ['Bandrek', 'Kopi Hitam'], 
                                'Harga': [4500, 3200]})
minuman_df

      Minuman  Harga
0     Bandrek   4500
1  Kopi Hitam   3200

In [13]:
minuman_df.to_csv('./output/minuman.csv')

#### Menyimpan DataFrame ke dalam file CSV tanpa menyertakan index

In [14]:
minuman_df.to_csv('./output/minuman.csv', index=False)

## Melakukan akses pada kolom DataFrame

In [15]:
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Terdapat dua cara untuk melakukan akses kolom pada DataFrame

### Cara 1: Sebagai atribute

In [16]:
wine_df.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

### Cara 2: Sebagai dictionary index

In [17]:
wine_df['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [18]:
wine_df['country'][0]

'Italy'

## Melakukan akses data pada DataFrame

Terdapat dua mekanisme untuk melakukan akses data pada DataFrame: index-based selection dan label-based selection. <br/>
Kedua mekanisme akses ini mendahulukan baris (row) baru diikuti kolom (column).

### index-based selection
Mekanisme ini dapat dilakukan dengan memanfaatkan method ```iloc```

In [19]:
wine_df.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [20]:
wine_df.iloc[2, 0]

'US'

#### Slicing pada iloc

In [21]:
wine_df.iloc[:, 0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [22]:
wine_df.iloc[0, :7]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
designation                                         Vulkà Bianco
points                                                        87
price                                                        NaN
province                                       Sicily & Sardinia
region_1                                                    Etna
Name: 0, dtype: object

In [23]:
wine_df.iloc[1:3, 0]

1    Portugal
2          US
Name: country, dtype: object

#### Melewatkan list untuk melakukan akses data pada baris dan kolom tertentu dari DataFrame

In [24]:
wine_df.iloc[[0, 3, 8], 0]

0      Italy
3         US
8    Germany
Name: country, dtype: object

#### Menggunakan negative index untuk melakukan akses data pada baris dan kolom tertentu dari DataFrame

In [25]:
wine_df.iloc[-5:]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### label-based selection
Mekanisme ini dapat dilakukan dengan memanfaatkan method ```loc```

In [26]:
wine_df.loc[0, 'country']

'Italy'

In [27]:
wine_df.loc[0:5, 'country']

0       Italy
1    Portugal
2          US
3          US
4          US
5       Spain
Name: country, dtype: object

In [28]:
wine_df.loc[:, ['taster_name', 'taster_twitter_handle', 'points']].head()

          taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
2        Paul Gregutt           @paulgwine       87
3  Alexander Peartree                   NaN      87
4        Paul Gregutt           @paulgwine       87

### Alternatif lain
Alternatif lain untuk melakukan akses data dapat dilakukan dengan model akses kolom-baris (column-row)

In [29]:
wine_df[['country', 'province']][:].head()

    country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro
2        US             Oregon
3        US           Michigan
4        US             Oregon

In [30]:
wine_df[['country', 'province']][:5]

    country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro
2        US             Oregon
3        US           Michigan
4        US             Oregon

## Mengganti index

In [31]:
wine_df.set_index('title').head()
# df = wine_df.set_index('title')
# wine_df.set_index('title', inplace=True)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

In [32]:
wine_df.reset_index().head()

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Seleksi data pada DataFrame
#### (Conditional Selection)

In [33]:
wine_df['country'] == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [34]:
wine_df.loc[wine_df['country'] == 'Italy'].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì

In [35]:
wine_df.loc[(wine_df['country'] == 'Italy') & (wine_df['points'] >= 90)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla

In [36]:
wine_df[(wine_df['country'] == 'Italy') & (wine_df['points'] >= 90)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla

## Mengenal beberapa built-in method 
#### Mengenal method ```isin```

In [37]:
wine_df.loc[wine_df['country'].isin(['Italy', 'France'])].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer

#### Mengenal method ```isna``` dan ```notna```

In [38]:
wine_df[wine_df['price'].isna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta

In [39]:
wine_df[wine_df['price'].notna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem

## Menambah kolom baru pada DataFrame

Mendata seluruh kolom yang tersedia dengan attribute ```columns```

In [40]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

Menambah kolom baru dengan nama ```critic``` dan diberi nilai ```everyone``` untuk tiap baris.

In [41]:
wine_df['critic'] = 'everyone'
wine_df['critic'].head(10)

0    everyone
1    everyone
2    everyone
3    everyone
4    everyone
5    everyone
6    everyone
7    everyone
8    everyone
9    everyone
Name: critic, dtype: object

In [42]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery', 'critic'],
      dtype='object')

Menambah kolom baru dengan nama ```index_backwards``` dan diberi nilai bilangan bulat dari besar ke kecil sesuai dengan banyaknya jumlah baris.

In [43]:
wine_df['index_backwards'] = range(len(wine_df), 0, -1)
wine_df['index_backwards'].head()

0    129971
1    129970
2    129969
3    129968
4    129967
Name: index_backwards, dtype: int64

## Menghasilkan ringkasan (summary) data pada DataFrame

#### Mengenal method ```describe```, ```mean```,  ```unique```, ```value_counts```

In [44]:
wine_df.describe()

              points          price  index_backwards
count  129971.000000  120975.000000    129971.000000
mean       88.447138      35.363389     64986.000000
std         3.039730      41.022218     37519.540256
min        80.000000       4.000000         1.000000
25%        86.000000      17.000000     32493.500000
50%        88.000000      25.000000     64986.000000
75%        91.000000      42.000000     97478.500000
max       100.000000    3300.000000    129971.000000

In [45]:
wine_df['points'].describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [46]:
wine_df['points'].mean()

88.44713820775404

In [47]:
wine_df['taster_name'].describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [48]:
wine_df['taster_name'].unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [49]:
wine_df['taster_name'].value_counts().head()

Roger Voss           25514
Michael Schachner    15134
Kerin O’Keefe        10776
Virginie Boone        9537
Paul Gregutt          9532
Name: taster_name, dtype: int64

## Mengenal Mapping
Terdapat dua mekanisme mapping pada DataFrame, yaitu: dengan memanfaatkan method ```map``` dan method ```apply```

### Mengenal method ```map```
Diterapkan di tingkat Series

In [50]:
points_mean = wine_df['points'].mean()
wine_df['points'].map(lambda p: p - points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

### Mengenal method ```apply```
Diterapkan di tingkat DataFrame

In [51]:
points_mean = wine_df['points'].mean()

def remean_points(row):
    row['points'] = row['points'] - points_mean
    return row

wine_df.apply(remean_points, axis='columns').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967

### Alternatif lain dengan built-in operations
Mekanisme ini lebih cepat dan efisien (bila dibandingkan ```map``` dan ```apply```) tetapi tidak bisa menangani pemrosesan yang kompleks.

In [52]:
points_mean = wine_df['points'].mean()
wine_df['points'] - points_mean

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [53]:
wine_df['country'] + ' - ' + wine_df['region_1']

0                     Italy - Etna
1                              NaN
2           US - Willamette Valley
3         US - Lake Michigan Shore
4           US - Willamette Valley
                    ...
129966                         NaN
129967                 US - Oregon
129968             France - Alsace
129969             France - Alsace
129970             France - Alsace
Length: 129971, dtype: object

#### Kasus: Mencari title wine dengan proporsi points/price tertinggi dengan memanfaatkan method ```idmax```

In [54]:
wine_df.loc[(wine_df['points']/wine_df['price']).idxmax(), 'title']

'Bandit NV Merlot (California)'

In [55]:
wine_df['title'][(wine_df['points']/wine_df['price']).idxmax()]

'Bandit NV Merlot (California)'

Kasus: Mencari jumlah wine dengan description tropical dan fruity. Siapkan series untuk menampung jumlah dari kedua data.

In [56]:
n_tropical = wine_df['description'].map(lambda desc: 'tropical' in desc).sum()
n_fruity = wine_df['description'].map(lambda desc: 'fruity' in desc).sum()
pd.Series([n_tropical, n_fruity], index=['tropical', 'fruity'])

tropical    3607
fruity      9090
dtype: int64

#### Kasus: Melakukan konversi point menjadi star

In [57]:
def star_converter(row):
    if row['country'] == 'Canada':
        row['star'] = 3
    elif row['points'] >= 95:
        row['star'] = 3
    elif row['points'] >= 85:
        row['star'] = 2
    else:
        row['star'] = 1
    return row

wine_df['star'] = None
wine_df.apply(star_converter, axis='columns').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971,2
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970,2
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969,2
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968,2
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967,2

## Analisis terhadap sekelompok data

#### Kasus: menghitung jumlah data (rows/baris) untuk tiap points. <br/>
Cara pertama: dengan memanfaatkan method ```value_counts```

In [58]:
wine_df['points'].value_counts().head()

88    17207
87    16933
90    15410
86    12600
89    12226
Name: points, dtype: int64

Cara kedua: mengelompokkan data pada DataFrame terlebih dahulu dengan memanfaatkan method ```groupby```

In [59]:
wine_df.groupby('points')['points'].count().head()

points
80     397
81     692
82    1836
83    3025
84    6480
Name: points, dtype: int64

#### Kasus: mendata wine reviewer beserta jumlah review yang pernah dilakukan.
Reviewer dapat diidentifikasi melalui kolom ```taster_name```

In [60]:
wine_df.groupby('taster_name')['taster_name'].count().head()

taster_name
Alexander Peartree     415
Anna Lee C. Iijima    4415
Anne Krebiehl MW      3685
Carrie Dykes           139
Christina Pickard        6
Name: taster_name, dtype: int64

#### Kasus: mencari harga terrendah dari setiap kelompok point

In [61]:
wine_df.groupby('points')['price'].min().head()

points
80    5.0
81    5.0
82    4.0
83    4.0
84    4.0
Name: price, dtype: float64

#### Kasus: menampilkan title dari wine untuk tiap country dengan points tertinggi
Data wine akan dikelompokkan terlebih dahulu berdasarkan negara, selanjutnya akan dicari wine di tiap kelompok negara yang memiliki points tertinggi

In [62]:
wine_df.groupby('country').apply(lambda df: df[ df['points'] == df['points'].max() ])[['title']].head()

                                                                           title
country
Argentina              82754   Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
Armenia                66146         Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia              345     Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Austria                109406  Kracher 2008 Zwischen den Seen Nummer 9 Trocke...
Bosnia and Herzegovina 96759                 Winery Čitluk 2011 Blatina (Mostar)

#### Kasus: menampilkan title dari wine untuk tiap proviince di tiap country dengan points tertinggi

In [63]:
wine_df.groupby(['country','province']).apply(lambda df: df[ df['points'] == df['points'].max() ])[['title']].head()

                                                                              title
country   province
Argentina Mendoza Province 82754  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other            78303                 Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia          66146        Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other  37882  Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales  85337  De Bortoli 2007 Noble One Bortytis Semillon (N...

### Mengenal method ```agg```

In [64]:
wine_df.groupby('country')['price'].agg([len, min, max]).head()

                         len   min     max
country
Argentina               3800   4.0   230.0
Armenia                    2  14.0    15.0
Australia               2329   5.0   850.0
Austria                 3345   7.0  1100.0
Bosnia and Herzegovina     2  12.0    13.0

#### Kasus: menampilkan harga (```price```) terrendah dan tertinggi untuk setiap jenis wine (```variety```)

In [65]:
wine_df.groupby('variety')['price'].agg(['min', 'max']).head()

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0

## Mengenal pengurutan data (sorting)

Membuat DataFrame yang lebih sederhana dengan tiga kolom

In [66]:
wine_simple_df = wine_df[['country', 'title', 'price']]
wine_simple_df.head()

    country                                              title  price
0     Italy                  Nicosia 2013 Vulkà Bianco  (Etna)    NaN
1  Portugal      Quinta dos Avidagos 2011 Avidagos Red (Douro)   15.0
2        US      Rainstorm 2013 Pinot Gris (Willamette Valley)   14.0
3        US  St. Julian 2013 Reserve Late Harvest Riesling ...   13.0
4        US  Sweet Cheeks 2012 Vintner's Reserve Wild Child...   65.0

#### Mengurutkan data berdasarkan price

In [67]:
wine_simple_df.sort_values(by='price').head()

       country                                             title  price
20484       US            Dancing Coyote 2015 White (Clarksburg)    4.0
112919   Spain  Terrenal 2010 Estate Bottled Tempranillo (Yecla)    4.0
59507       US   Pam's Cuties NV Unoaked Chardonnay (California)    4.0
31530       US                 Bandit NV Chardonnay (California)    4.0
61768    Spain          Terrenal 2010 Cabernet Sauvignon (Yecla)    4.0

#### Pengurutan secara descending (dari nilai terbesar ke nilai terkecil)

In [68]:
wine_simple_df.sort_values(by='price', ascending=False).head()

       country                                              title   price
80290   France               Château les Ormes Sorbet 2013  Médoc  3300.0
15840   France                       Château Pétrus 2014  Pomerol  2500.0
98380   France     Domaine du Comte Liger-Belair 2010  La Romanée  2500.0
120391      US  Blair 2013 Roger Rose Vineyard Chardonnay (Arr...  2013.0
113564  France     Domaine du Comte Liger-Belair 2005  La Romanée  2000.0

In [69]:
wine_simple_df.sort_values(by=['country', 'title']).head()

         country                                              title  price
5902   Argentina                         2 Copas 2009 Red (Mendoza)    8.0
45568  Argentina      25 Lagunas 2014 Cabernet Sauvignon (San Juan)   10.0
9790   Argentina  Achaval-Ferrer 2006 Finca Altamira Malbec (La ...  112.0
73744  Argentina  Achaval-Ferrer 2007 Finca Mirador Malbec (Medr...  112.0
7076   Argentina               Achaval-Ferrer 2007 Malbec (Mendoza)   29.0

#### Kasus: menampilkan daftar harga terrendah dan tertinggi untuk setiap variety wine, data diurutkan secara descending berdasarkan harga terrendah dan diikuti harga tertinggi.

In [70]:
wine_df.groupby('variety')['price'].agg(['min', 'max']).sort_values(by=['min','max'], ascending=False).head()

                    min    max
variety
Ramisco           495.0  495.0
Terrantez         236.0  236.0
Francisa          160.0  160.0
Rosenmuskateller  150.0  150.0
Tinta Negra Mole  112.0  112.0

#### Kasus: menampilkan rata-rata points yang diberikan oleh tiap reviewer (```taster_name```)

In [71]:
wine_df.groupby('taster_name')['points'].mean().head()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Name: points, dtype: float64

#### Kasus: menampilkan jumlah wine (```title```) yang dihasilkan di tiap negara (```country```) untuk tiap jenis wine (```variety```)

In [72]:
wine_df.groupby(['country', 'variety'])['title'].count().sort_values(ascending=False).head(10)

country  variety
US       Pinot Noir                  9885
         Cabernet Sauvignon          7315
         Chardonnay                  6801
France   Bordeaux-style Red Blend    4725
Italy    Red Blend                   3624
US       Syrah                       3244
         Red Blend                   2972
France   Chardonnay                  2808
Italy    Nebbiolo                    2736
US       Zinfandel                   2711
Name: title, dtype: int64

## Mengubah nama kolom pada DataFrame
Perubahan nama kolom pada DataFrame dapat dilakukan dengan memanfaatkan method ```rename```

In [73]:
wine_df.rename(columns={'points': 'score'}).head()

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967,None

#### Mengubah label/nama index dengan method ```rename_axis```

In [74]:
wine_df.rename_axis('baris', axis='rows').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
baris,,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967,None

In [75]:
wine_df.rename_axis('baris', axis='rows').rename_axis('kolom', axis='columns').head()

kolom,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
baris,,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967,None

## Referensi Belajar
### Struktur Data bawaan (built-in) pada pemrograman Python

In [76]:
# YouTubeVideo('3Og1xO15HhQ')

### Pythonic: Penulisan kode Python yang idiomatic

In [77]:
# YouTubeVideo('BHP3J8akr74')

### HackerRank: Latihan soal pemrograman Python

In [78]:
# YouTubeVideo('kwlRZUjzsns')

### Statistika Deskriptif

In [79]:
# YouTubeVideo('el7Ezn9PpWU')